import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Quiz",
	description: "Generated by create next app",
	icons: "/springboot-inner.svg",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased">
				<AntdRegistry>
					<Theme>{children}</Theme>
				</AntdRegistry>
			</body>
		</html>
	);
}
